export default function CloudFeatureSupportTable() {
  // TODO: 把下面这个表格用组件重构了
  return (
    <div>
      <ul>
        <li>Y: 支持(增删查改)</li>
        <li>N: 不支持</li>
        <li>-: 平台本身不支持</li>
        <li>D: 开发过程中</li>
        <li>R: 只读同步</li>
      </ul>
      <table>
        <thead>
          <tr>
            <th>云平台(Provider)</th>
            <th>虚拟机</th>
            <th>区域</th>
            <th>可用区</th>
            <th>项目</th>
            <th>镜像</th>
            <th>安全组</th>
            <th>磁盘</th>
            <th>快照</th>
            <th>宿主机</th>
            <th>VPC</th>
            <th>弹性网卡</th>
            <th>二层网络</th>
            <th>EIP</th>
            <th>NAT</th>
            <th>负载均衡</th>
            <th>WAF</th>
            <th>DNS</th>
            <th>VPC互联</th>
            <th>VPC对等连接</th>
            <th>路由表</th>
            <th>CDN</th>
            <th>IPv6网关</th>
            <th>RDS</th>
            <th>MongoDB</th>
            <th>弹性缓存</th>
            <th>对象存储</th>
            <th>NAS</th>
            <th>Kafka</th>
            <th>Elasticsearch</th>
            <th>应用程序服务</th>
            <th>容器</th>
            <th>IAM</th>
            <th>标签</th>
            <th>操作日志</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>内置私有云(Cloudpods)</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>-</td>
            <td>Y</td>
            <td>-</td>
            <td>Y</td>
            <td>-</td>
            <td>-</td>
            <td>Y</td>
            <td>N</td>
            <td>-</td>
            <td>-</td>
            <td>N</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
          </tr>
          <tr>
            <td>阿里云(Aliyun)</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>-</td>
            <td>Y</td>
            <td>R</td>
            <td>-</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>R</td>
            <td>Y</td>
            <td>R</td>
            <td>N</td>
            <td>R</td>
            <td>R</td>
            <td>N</td>
            <td>Y</td>
            <td>R</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>R</td>
            <td>N</td>
            <td>N</td>
            <td>R</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
          </tr>
          <tr>
            <td>腾讯云(Qcloud)</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>-</td>
            <td>Y</td>
            <td>R</td>
            <td>-</td>
            <td>Y</td>
            <td>R</td>
            <td>Y</td>
            <td>N</td>
            <td>Y</td>
            <td>R</td>
            <td>R</td>
            <td>R</td>
            <td>R</td>
            <td>N</td>
            <td>Y</td>
            <td>R</td>
            <td>Y</td>
            <td>Y</td>
            <td>N</td>
            <td>R</td>
            <td>R</td>
            <td>N</td>
            <td>R</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
          </tr>
          <tr>
            <td>华为云(Huawei)</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>-</td>
            <td>Y</td>
            <td>R</td>
            <td>-</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>R</td>
            <td>R</td>
            <td>N</td>
            <td>N</td>
            <td>Y</td>
            <td>N</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
          </tr>
          <tr>
            <td>微软云(Azure)</td>
            <td>Y</td>
            <td>Y</td>
            <td>-</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>-</td>
            <td>Y</td>
            <td>R</td>
            <td>-</td>
            <td>Y</td>
            <td>-</td>
            <td>R</td>
            <td>R</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>R</td>
            <td>N</td>
            <td>N</td>
            <td>Y</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>R</td>
            <td>R</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
          </tr>
          <tr>
            <td>谷歌云(Google)</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>-</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>-</td>
            <td>Y</td>
            <td>-</td>
            <td>-</td>
            <td>Y</td>
            <td>N</td>
            <td>R</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>Y</td>
            <td>N</td>
            <td>N</td>
            <td>Y</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>Y</td>
            <td>Y</td>
            <td>N</td>
          </tr>
          <tr>
            <td>AWS(AWS)</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>N</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>-</td>
            <td>Y</td>
            <td>N</td>
            <td>-</td>
            <td>Y</td>
            <td>R</td>
            <td>Y</td>
            <td>R</td>
            <td>Y</td>
            <td>N</td>
            <td>R</td>
            <td>R</td>
            <td>N</td>
            <td>N</td>
            <td>Y</td>
            <td>N</td>
            <td>N</td>
            <td>Y</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
          </tr>
          <tr>
            <td>优刻得(Ucloud)</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>N</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>-</td>
            <td>Y</td>
            <td>Y</td>
            <td>-</td>
            <td>Y</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>Y</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
          </tr>
          <tr>
            <td>天翼云(Ctyun)</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>N</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>N</td>
            <td>-</td>
            <td>Y</td>
            <td>N</td>
            <td>-</td>
            <td>Y</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
          </tr>
          <tr>
            <td>移动云(Ecloud)</td>
            <td>R</td>
            <td>Y</td>
            <td>Y</td>
            <td>N</td>
            <td>R</td>
            <td>R</td>
            <td>R</td>
            <td>N</td>
            <td>-</td>
            <td>R</td>
            <td>-</td>
            <td>-</td>
            <td>R</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
          </tr>
          <tr>
            <td>京东云(JDcloud)</td>
            <td>R</td>
            <td>Y</td>
            <td>Y</td>
            <td>N</td>
            <td>R</td>
            <td>R</td>
            <td>R</td>
            <td>R</td>
            <td>-</td>
            <td>R</td>
            <td>N</td>
            <td>-</td>
            <td>R</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
          </tr>
          <tr>
            <td>VMware(VMware)</td>
            <td>Y</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>Y</td>
            <td>-</td>
            <td>Y</td>
            <td>N</td>
            <td>R</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>N</td>
            <td>N</td>
            <td>-</td>
            <td>N</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>N</td>
            <td>-</td>
            <td>-</td>
            <td>N</td>
            <td>-</td>
            <td>N</td>
            <td>-</td>
          </tr>
          <tr>
            <td>OpenStack(OpenStack)</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>N</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>R</td>
            <td>Y</td>
            <td>R</td>
            <td>-</td>
            <td>Y</td>
            <td>N</td>
            <td>Y</td>
            <td>-</td>
            <td>N</td>
            <td>-</td>
            <td>-</td>
            <td>R</td>
            <td>N</td>
            <td>N</td>
            <td>-</td>
            <td>N</td>
            <td>-</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>-</td>
            <td>-</td>
            <td>N</td>
            <td>N</td>
            <td>Y</td>
            <td>N</td>
          </tr>
          <tr>
            <td>DStack(DStack)</td>
            <td>Y</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>R</td>
            <td>Y</td>
            <td>R</td>
            <td>-</td>
            <td>Y</td>
            <td>-</td>
            <td>N</td>
            <td>-</td>
            <td>N</td>
            <td>-</td>
            <td>-</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>-</td>
            <td>N</td>
            <td>-</td>
            <td>-</td>
            <td>N</td>
            <td>N</td>
            <td>-</td>
            <td>-</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
          </tr>
          <tr>
            <td>ZStack(ZStack)</td>
            <td>Y</td>
            <td>-</td>
            <td>Y</td>
            <td>N</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>R</td>
            <td>Y</td>
            <td>R</td>
            <td>-</td>
            <td>Y</td>
            <td>-</td>
            <td>N</td>
            <td>-</td>
            <td>N</td>
            <td>-</td>
            <td>-</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>-</td>
            <td>N</td>
            <td>-</td>
            <td>-</td>
            <td>N</td>
            <td>N</td>
            <td>-</td>
            <td>-</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
          </tr>
          <tr>
            <td>阿里私有云(Apsara)</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>N</td>
            <td>R</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>-</td>
            <td>Y</td>
            <td>R</td>
            <td>-</td>
            <td>Y</td>
            <td>R</td>
            <td>Y</td>
            <td>-</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>R</td>
            <td>N</td>
            <td>R</td>
            <td>Y</td>
            <td>N</td>
            <td>Y</td>
            <td>-</td>
            <td>N</td>
            <td>N</td>
            <td>-</td>
            <td>-</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
          </tr>
          <tr>
            <td>HCSO</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>N</td>
            <td>R</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>-</td>
            <td>Y</td>
            <td>R</td>
            <td>-</td>
            <td>Y</td>
            <td>R</td>
            <td>R</td>
            <td>-</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>Y</td>
            <td>N</td>
            <td>N</td>
            <td>-</td>
            <td>N</td>
            <td>N</td>
            <td>-</td>
            <td>-</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
            <td>N</td>
          </tr>
          <tr>
            <td>Nutainx</td>
            <td>Y</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>Y</td>
            <td>-</td>
            <td>Y</td>
            <td>N</td>
            <td>R</td>
            <td>Y</td>
            <td>R</td>
            <td>Y</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>N</td>
            <td>-</td>
            <td>N</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>N</td>
            <td>-</td>
            <td>-</td>
            <td>N</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
          </tr>
          <tr>
            <td>品高云(BingoCloud)</td>
            <td>Y</td>
            <td>-</td>
            <td>-</td>
            <td>N</td>
            <td>N</td>
            <td>-</td>
            <td>Y</td>
            <td>N</td>
            <td>Y</td>
            <td>Y</td>
            <td>Y</td>
            <td>N</td>
            <td>Y</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
          </tr>
          <tr>
            <td>浪潮云(inCloud Sphere)</td>
            <td>R</td>
            <td>Y</td>
            <td>Y</td>
            <td>-</td>
            <td>N</td>
            <td>N</td>
            <td>R</td>
            <td>N</td>
            <td>Y</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
          </tr>
          <tr>
            <td>S3(S3)</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>Y</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
          </tr>
          <tr>
            <td>Ceph(Ceph)</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>Y</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
          </tr>
          <tr>
            <td>Xsky(Xsky)</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>Y</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
          </tr>
        </tbody>
      </table>
    </div>
  )
}