import styles from './styles.module.css';
export default function CloudFeatureSupportTable() {
  // TODO: 把下面这个表格用组件重构了
  return (
    <div>
      <ul>
        <li>Y: 支持(增删查改)</li>
        <li>N: 不支持</li>
        <li>-: 平台本身不支持</li>
        <li>D: 开发过程中</li>
        <li>R: 只读同步</li>
      </ul>
      
    <table>
    <tr>
        <th rowspan="2" class="fixed-row-1 fixed-col-1" style={{zIndex: 3}}> 分类 </th>
        <th rowspan="2" class="fixed-row-1 fixed-col-2" style={{zIndex: 3}}>云资源类型</th>
        <th style={{textAlign: 'center'}} class="fixed-row-1" colspan="16">公有云</th>
        <th style={{textAlign: 'center'}} class="fixed-row-1" colspan="14">私有云</th>
    </tr>
    <tr>
        <th class="fixed-row-2">阿里云</th>
        <th class="fixed-row-2">阿里金融云</th>
        <th class="fixed-row-2">腾讯云</th>
        <th class="fixed-row-2">华为云</th>
        <th class="fixed-row-2">AWS</th>
        <th class="fixed-row-2">Azure</th>
        <th class="fixed-row-2">GCP</th>
        <th class="fixed-row-2">火山引擎</th>
        <th class="fixed-row-2">UCloud</th>
        <th class="fixed-row-2">天翼云</th>
        <th class="fixed-row-2">移动云</th>
        <th class="fixed-row-2">京东云</th>
        <th class="fixed-row-2">百度云</th>
        <th class="fixed-row-2">联通云</th>
        <th class="fixed-row-2">金山云</th>
        <th class="fixed-row-2">青云</th>
        <th class="fixed-row-2">阿里飞天 (3.12+)</th>
        <th class="fixed-row-2">HCSO</th>
        <th class="fixed-row-2">HCS (8.0.3+)</th>
        <th class="fixed-row-2">ZStack (3.4.0+)</th>
        <th class="fixed-row-2">OpenStack (M+)</th>
        <th class="fixed-row-2">VMware (6.5+)</th>
        <th class="fixed-row-2">Cloudpods</th>
        <th class="fixed-row-2">DStack</th>
        <th class="fixed-row-2">Nutanix (6.5.2+)</th>
        <th class="fixed-row-2">BingoCloud</th>
        <th class="fixed-row-2">inCloud Sphere (6.5.1+)</th>
        <th class="fixed-row-2">外部数据</th>
        <th class="fixed-row-2">Proxmox (6.3+)</th>
        <th class="fixed-row-2">H3C (CloudOS 5.0+)</th>
    </tr>
    <tr>
        <th rowspan="7" class="fixed-col-1">主机</th>
        <th class="fixed-col-2">虚拟机</th>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>         
    </tr>
    <tr>
        <th class="fixed-col-2">弹性伸缩组</th>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td></td> 
    </tr>
    <tr>
        <th class="fixed-col-2">系统镜像</th>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td> 
    </tr>
    <tr>
        <th class="fixed-col-2">硬盘</th>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td> 
    </tr>
    <tr>
        <th class="fixed-col-2">快照</th>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td> 
    </tr>
    <tr>
        <th class="fixed-col-2">自动快照策略</th>
        <td>Y</td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td> 
    </tr>
    <tr>
        <th class="fixed-col-2">安全组</th>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td></td> 
    </tr>
    <tr>
        <th rowspan="9" class="fixed-col-1">网络</th>
        <th class="fixed-col-2">专有网络VPC</th>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td>Y</td> 
    </tr>
    <tr>
        <th class="fixed-col-2">IP子网</th>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td>Y</td> 
    </tr>
    <tr>
    <th class="fixed-col-2">弹性公网IP</th>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td>Y</td> 
    </tr>
    <tr>
        <th class="fixed-col-2">NAT网关</th>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td> 
    </tr>
    <tr>
        <th class="fixed-col-2">DNS解析</th>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td> 
    </tr>
    <tr>
        <th class="fixed-col-2">负载均衡LB</th>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td>Y</td> 
    </tr>
    <tr>
        <th class="fixed-col-2">CDN</th>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td> 
    </tr>
    <tr>
        <th class="fixed-col-2">WAF</th>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td> 
    </tr>
    <tr>
        <th class="fixed-col-2">IPv6网关</th>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <th rowspan="3" class="fixed-col-1">存储</th>
        <th class="fixed-col-2">对象存储</th>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td></td> 
    </tr>
    <tr>
        <th class="fixed-col-2">NAS文件存储</th>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td> 
    </tr>
    <tr>
        <th class="fixed-col-2">表格存储</th>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td> 
    </tr>
    <tr>
        <th rowspan="3" class="fixed-col-1">数据库</th>
        <th class="fixed-col-2">RDS</th>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td>Y</td> 
    </tr>
    <tr>
        <th class="fixed-col-2">Redis</th>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td> 
    </tr>
    <tr>
        <th class="fixed-col-2">MongoDB</th>
        <td></td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td> 
    </tr>
    <tr>
        <th rowspan="2" class="fixed-col-1">中间件</th>
        <th class="fixed-col-2">Kafka</th>
        <td></td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <th class="fixed-col-2">Elasticsearch</th>
        <td></td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <th rowspan="2" class="fixed-col-1">容器</th>
        <th class="fixed-col-2">Kubernetes集群纳管</th>
        <td>Y</td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <th class="fixed-col-2">Kubernetes集群新建</th>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <th class="fixed-col-1">监控</th>
        <th class="fixed-col-2">监控告警</th>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <th class="fixed-col-1">费用</th>
        <th class="fixed-col-2">公有云账单分析/私有云计费服务</th>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <th rowspan="2" class="fixed-col-1">其他</th>
        <th class="fixed-col-2">公有云子账号</th>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <th class="fixed-col-2">免密登录云平台</th>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Y</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    </table>

    </div>
  )
}