/**
 * AI云文档侧边栏配置
 * 管理大语言模型等AI容器应用
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const aicloudSidebar = {
  aicloudSidebar: [
    // 侧边栏顶部固定标题
    {
      type: 'html',
      value: '<div class="sidebar-doc-type-title"><span class="sidebar-doc-type-icon" style="background: linear-gradient(135deg, #29784c 0%, #33925d 100%); width: 32px; height: 32px; border-radius: 6px; display: flex; align-items: center; justify-content: center;"><img src="/img/feature_cloud_native.svg" alt="AI云" style="width: 20px; height: 20px; filter: brightness(0) invert(1);" /></span><span class="sidebar-doc-type-label"><span class="sidebar-label-zh">AI云</span><span class="sidebar-label-en">AI Cloud</span></span><span class="sidebar-doc-type-desc" style="display:block;font-size:12px;color:var(--ifm-color-content-secondary);margin-top:4px;"></div>',
      defaultStyle: true,
    },
    // 自动生成当前文档实例的所有文档
    { type: 'autogenerated', dirName: '.' },
  ],
};

module.exports = aicloudSidebar;
