/**
 * 私有云管理文档侧边栏配置
 * 使用自动生成 + 手动链接通用文档的方式
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const onpremiseSidebar = {
  onpremiseSidebar: [
    // 侧边栏顶部固定标题
    {
      type: 'html',
      value: '<div class="sidebar-doc-type-title"><span class="sidebar-doc-type-icon">🏢</span><span class="sidebar-doc-type-label">私有云管理</span></div>',
      defaultStyle: true,
    },
    // 自动生成当前文档实例的所有文档（包括通过符号链接引用的升级文档）
    { type: 'autogenerated', dirName: '.' },
  ],
};

module.exports = onpremiseSidebar;

