/**
 * 私有云管理文档侧边栏配置
 * 使用自动生成 + 手动链接通用文档的方式
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const onpremiseSidebar = {
  onpremiseSidebar: [
    // 自动生成当前文档实例的所有文档（包括通过符号链接引用的升级文档）
    { type: 'autogenerated', dirName: '.' },
  ],
};

module.exports = onpremiseSidebar;

