/**
 * 共享文档侧边栏配置
 * 包含所有产品通用的文档
 * 使用自动生成 + 手动分类的方式
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sharedSidebar = {
  sharedSidebar: [
    // 自动生成所有文档，根据文件结构组织
    { type: 'autogenerated', dirName: '.' },
  ],
};

module.exports = sharedSidebar;

